### ISSUE TITLE
Wrong balance calculus

### ISSUE THREAD

**Issue by igorline** [lyra-finance/lyra-vaults#29]
https://github.com/lyra-finance/lyra-vaults/blob/34283f1b40bf27d2fb087401069a7e1a3868c489/contracts/core/BaseVault.sol#L500

As the assets currently are staying in the vault when round is started you'd be getting balance twice bigger than it should be.
We solved this by transferring assets on the round start: https://github.com/fuertefi/lyra-ethglobal/blob/main/packages/contracts/contracts/core/HackMoneyVault.sol#L141-L144

**Comment by rokusk** [comment]
good catch! this will cause some view function to return wrong value and break the cap as well.
